version: "3.8"

services:
  espocrm-db:
    image: mariadb:latest
    container_name: espocrm-db
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME:-espocrm}
      MARIADB_USER: ${DB_USER:-espocrm}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ../files/espocrm-db:/var/lib/mysql
    networks:
      - dokploy-network
    restart: always

  espocrm:
    # BUILD FROM DOCKERFILE INSTEAD OF IMAGE
    build:
      context: .
      dockerfile: Dockerfile
    container_name: espocrm
    environment:
      ESPOCRM_DATABASE_PLATFORM: Mysql
      ESPOCRM_DATABASE_HOST: espocrm-db
      ESPOCRM_DATABASE_USER: ${DB_USER:-espocrm}
      ESPOCRM_DATABASE_PASSWORD: ${DB_PASSWORD}
      ESPOCRM_DATABASE_NAME: ${DB_NAME:-espocrm}
      ESPOCRM_ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ESPOCRM_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ESPOCRM_SITE_URL: "https://${DOMAIN}"
    volumes:
      - ../files/espocrm-data:/var/www/html/data
      - ../files/espocrm-uploads:/var/www/html/data/upload
    networks:
      - dokploy-network
    restart: always
    depends_on:
      - espocrm-db
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.espocrm.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.espocrm.entrypoints=websecure"
      - "traefik.http.routers.espocrm.tls=true"
      - "traefik.http.routers.espocrm.tls.certResolver=letsencrypt"
      - "traefik.http.services.espocrm.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true